## Introduction to gradients and automatic differentiation 

In [1]:
import numpy as np
import matplotlib.pyplot as plt

import tensorflow as tf

In [2]:
x = tf.Variable(3.0)

with tf.GradientTape() as tape:
  y = x**2

In [3]:
y

<tf.Tensor: shape=(), dtype=float32, numpy=9.0>

In [4]:
# dy = 2x * dx
dy_dx = tape.gradient(y, x)
dy_dx.numpy()

6.0

In [5]:
# The above example uses scalars, but tf.GradientTape works as easily on any tensor:

In [17]:
w = tf.Variable(tf.random.normal((3, 2)), name='w')
b = tf.Variable(tf.zeros(2, dtype=tf.float32), name='b')
x = [[1., 2., 3.]]

with tf.GradientTape(persistent=True) as tape:
  y = x @ w + b
  loss = tf.reduce_mean(y**2)

In [7]:
[dl_dw, dl_db] = tape.gradient(loss, [w, b])

In [8]:
print(w.shape)
print(dl_dw.shape)

(3, 2)
(3, 2)


In [9]:
w

<tf.Variable 'w:0' shape=(3, 2) dtype=float32, numpy=
array([[ 1.03333   ,  0.42647403],
       [ 1.036649  , -1.5083102 ],
       [ 0.96885073, -0.66818607]], dtype=float32)>

In [10]:
dl_dw

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[  6.0131803,  -4.5947046],
       [ 12.0263605,  -9.189409 ],
       [ 18.039541 , -13.784114 ]], dtype=float32)>

In [11]:
my_vars = {
    'w': w,
    'b': b
}

grad = tape.gradient(loss, my_vars)
grad['b']

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 6.0131803, -4.5947046], dtype=float32)>

In [12]:
## Here is the gradient calculation again, this time passing a dictionary of variables:

In [13]:
my_vars = {
    'w': w,
    'b': b
}

grad = tape.gradient(loss, my_vars)
grad['b']

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 6.0131803, -4.5947046], dtype=float32)>

In [18]:
## tape watch is used to watch the variables

In [27]:
x0 = tf.Variable(0.0)
x1 = tf.Variable(10.0)

with tf.GradientTape(watch_accessed_variables=False) as tape:
  tape.watch(x1)
  y0 = tf.math.sin(x0)
  y1 = tf.nn.softplus(x1)
  y = y0 + y1
  ys = tf.reduce_sum(y)
  grad = tape.gradient(ys, {'x0': x0, 'x1': x1})

  print('dy/dx0:', grad['x0'])
  print('dy/dx1:', grad['x1'])

dy/dx0: None
dy/dx1: tf.Tensor(0.9999546, shape=(), dtype=float32)
